=== BViktor10/ZY5P7FWebXML/ZY5P7F_1008/ZY5P7F_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ZY5P7F_orarend">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ora" type="oraTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="oraTipus">
		<xs:sequence>
			<xs:element name="targy" type="targyTipus"/>
			<xs:element name="idopont" type="idopontTipus"/>
			<xs:element name="helyszin" type="helyszinTipus"/>
			<xs:element name="oktato" type="oktatoTipus"/>
			<xs:element name="szak" type="szakTipus"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
		<xs:attribute name="tipus" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="targyTipus">
		<xs:attribute name="nev" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="idopontTipus">
		<xs:sequence>
			<xs:element name="nap" type="napTipus"/>
			<xs:element name="tol" type="tolTipus"/>
			<xs:element name="ig" type="igTipus"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="napTipus">
		<xs:attribute name="napn" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="tolTipus">
		<xs:attribute name="tolt" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="igTipus">
		<xs:attribute name="igt" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="helyszinTipus">
		<xs:attribute name="hol" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="oktatoTipus">
		<xs:attribute name="neve" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="szakTipus">
		<xs:attribute name="sznev" type="xs:string" use="required"/>
	</xs:complexType>

</xs:schema>

=== BViktor10/ZY5P7FWebXML/ZY5P7F_1008/ZY5P7F_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZY5P7F_orarend
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ZY5P7F_orarend.xsd">
	<ora id="2" tipus="eloadas">
		<targy nev="Vállalati Információs Rendszerek Fejleszése"></targy>
		<idopont>
			<nap napn="Szerda"></nap>
			<tol tolt="14:00"></tol>
			<ig igt="16:00"></ig>
		</idopont>
		<helyszin hol="Inf 103"></helyszin>
		<oktato neve="Dr. Sasvári Péter László "></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>
	
	<ora id="3" tipus="eloadas">
		<targy nev="Mesterséges Intelligencia"></targy>
		<idopont>
			<nap napn="kedd"></nap>
			<tol tolt="10:00"></tol>
			<ig igt="12:00"></ig>
		</idopont>
		<helyszin hol="A1 32 ea."></helyszin>
		<oktato neve="Dr. Kunné Tamási Judit"></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>
	
	<ora id="4" tipus="eloadas">
		<targy nev="Adatkezelés XML-ben"></targy>
		<idopont>
			<nap napn="szerda"></nap>
			<tol tolt="8:00"></tol>
			<ig igt="10:00"></ig>
		</idopont>
		<helyszin hol="T050"></helyszin>
		<oktato neve="Prof. Dr. Kovács László"></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>

	<ora id="7" tipus="gyakorlat">
		<targy nev="Vállalati Információs Rendszerek Fejlesztése"></targy>
		<idopont>
			<nap napn="szerda"></nap>
			<tol tolt="18:00"></tol>
			<ig igt="20:00"></ig>
		</idopont>
		<helyszin hol="Inf 103"></helyszin>
		<oktato neve="Dr. Sasvári Péter László"></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>
	
	<ora id="8" tipus="gyakorlat">
		<targy nev="Adatkezelés XML-ben"></targy>
		<idopont>
			<nap napn="szerda"></nap>
			<tol tolt="10:00"></tol>
			<ig igt="12:00"></ig>
		</idopont>
		<helyszin hol="Inf 101"></helyszin>
		<oktato neve="Dr. Bednarik László"></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>
	
	<ora id="11" tipus="gyakorlat">
		<targy nev="Mesterséges Intelligencia"></targy>
		<idopont>
			<nap napn="kedd"></nap>
			<tol tolt="12:00"></tol>
			<ig igt="14:00"></ig>
		</idopont>
		<helyszin hol="A1 32 ea."></helyszin>
		<oktato neve="Fazekas Levente"></oktato>
		<szak sznev="Programtervező Informatika"></szak>
	</ora>
	
</ZY5P7F_orarend>
